ttsx/cart/urls.py
from django.conf.urls import url
import views
urlpatterns = [
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^islogin/$',views.islogin,name='islogin'),
    url(r'^add/$',views.add,name='add'),
    url(r'^count1/$',views.count1,name='count1'),
    url(r'^save_count/$',views.save_count,name='save_count'),
    url(r'^del_cart/$',views.del_cart,name='del_cart'),
]

ttsx/goods/urls.py
from django.conf.urls import url

from goods.search_view import MySearchView
from . import views
urlpatterns = [
    url(r'^index/$',views.index,name='index'),
    url(r'^list(?P<tid>\d+)-(?P<pIndex>\d+)/$',views.list,name='list'),
    url(r'^(?P<tid>\d+)-(?P<gid>\d+)/$',views.detail,name='detail'),
    url(r'^search',MySearchView.as_view(),name='search'),
]

ttsx/ttsx/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls',namespace='user')),  # ,app_name='user'
    # url(r'^',include('user.urls')),
    url(r'^goods/',include('goods.urls',namespace='goods')),
    url(r'^tinymce/', include('tinymce.urls')),
    # url(r'^search/', include('haystack.urls')),
    url(r'^',include('goods.urls',namespace='goods')),
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url(r'^order/',include('order.urls',namespace='order')),
]

ttsx/user/urls.py
# coding=utf-8
from user import views
from django.conf.urls import url


urlpatterns = [
    # url(r'^index/$',views.index,name='index'),# name是别名，用来跟在命名空间后，拼成url
    url(r'^register/$',views.register,name='register'),
    url(r'^register_check/$',views.register_check, name='register_check'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_check/$',views.login_check,name='login_check'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^user_center_info/$',views.user_center_info,name='user_center_info'),
    url(r'^user_center_order/$',views.user_center_order,name='user_center_order'),
    url(r'^user_center_site/$', views.user_center_site,name='user_center_site'),
    url(r'^add_receive/$',views.add_receive,name='add_receive'),
    # url(r'^cart/$',views.cart,name='cart'),
    # url(r'^detail/$',views.detail,name='detail'),

]

ttsx/cart/models.py
from django.db import models

# Create your models here.
from user.models import UserInfo
from goods.models import GoodInfo


class CartInfo(models.Model):
    cuser = models.ForeignKey(UserInfo)
    cgood = models.ForeignKey(GoodInfo)
    ccount = models.IntegerField()

ttsx/cart/views.py
# coding=utf-8
from django.db.models import Sum
from django.shortcuts import render

from cart.models import CartInfo
from user import decorator
from django.http import JsonResponse
# Create your views here.
@decorator.islogin
def cart(request):
    uid = int(request.session.get('uid'))
    cart_goods = CartInfo.objects.filter(cuser_id=uid)
    context = {'title':'购物车','head':1,'logo_search':2,'cart_goods':cart_goods}
    return render(request,'cart.html',context)

# 加入购物车之前，判断是否已经登录
def islogin(request):
    if request.session.has_key('uid'):
        context = {'flag1':1}
        context['uid'] = request.session.get('uid')
    else:
        context = {'flag1':0}
    return JsonResponse(context)

# 添加购物车
def add(request):
    try:
        uid = int(request.session.get('uid'))
        gid = int(request.GET.get('gid'))
        gcount = int(request.GET.get('gcount', 1))
        cart = CartInfo.objects.filter(cuser_id=uid,cgood_id=gid)
        # 如果购物车中有这个商品，就只是数量增加count，否则新建一个商品，填入count
        if len(cart)==1:
            cart[0].ccount+=gcount
            cart[0].save()
        else:
            cart = CartInfo()
            cart.cuser_id = uid
            cart.cgood_id = gid
            cart.ccount = gcount
            cart.save()
        context = {'result':1,'gcount':gcount}
    except:
        context = {'result':0,'gcount':0}
    return JsonResponse(context)

def count1(request):
    uid = int(request.session.get('uid'))
    # 因为聚合函数返回的是字典样式{"ccount__sum": 60}，并不是个值，所以需要get取出来
    sum_count = CartInfo.objects.filter(cuser_id=uid).aggregate(Sum('ccount')).get('ccount__sum')
    return JsonResponse({'sum_count':sum_count})

def save_count(request):
    try:
        id = int(request.GET.get('id'))
        num = int(request.GET.get('num'))
        cart = CartInfo.objects.get(pk=id)
        cart.ccount = num
        cart.save()
        context = {'ok': 1}
    except:
        context = {'ok':0}
    return JsonResponse(context)

def del_cart(request):
    try:
        id = int(request.GET.get('id'))
        cart = CartInfo.objects.get(pk=id)
        cart.delete()
        context = {'ok':1}
    except:
        context = {'ok':0}
    return JsonResponse(context)

ttsx/templates/detail.html
{% extends 'father2.html' %}

{% block title %}<title>天天生鲜-商品详情</title>
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>


{% endblock title %}

{% block list_title %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ t.tname }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="/static/{{ good.gimg }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ good.gname }}</h3>
			<p>{{ good.glong_name }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ good.gprice }}</em></span>
				<span class="show_unit">单  位：{{ good.gunit }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
                <input type="hidden" id="stock" value="{{ good.gstock }}">
				<div class="num_add fl">
                    <input type="hidden" id="gid" value="{{ good.id }}">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>{{ good.gprice }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>
{% endblock list_title %}
{% block right %}
		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
                {{ good.gdetail|safe }}
			</div>

		</div>


{#</div>#}
	<div class="add_jump"></div>
    <script type="text/javascript">
    $(function () {
        {#              播放添加购物车的动画#}
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;

        $('#add_cart').click(function(){
            $.get('/cart/islogin/',function (data) {
                if(data.flag1){//已经登录
                    gid = parseInt($('#gid').val());
{#                添加的函数#}
                $.get('/cart/add/',{'gid':gid},function (data) {
                    var $count = data.gcount
                    if(data.result){//添加成功
                        $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'});
                        $(".add_jump").stop().animate({
                            'left': $to_y+7,
                            'top': $to_x+7},
                            "fast", function() {
                                $(".add_jump").fadeOut('fast',function(){
                                    var cart_all = $('#show_count').text();
                                    $('#show_count').html(parseInt(cart_all)+$count);
                                });
                            });
                    }else{//添加失败
                        alert('添加失败');
                    }
                });
                }else{//未登录
                    location.href = '/user/login/';
                }
            });
        });

        $('.num_show').blur(function () {
            re1 = '[1-9]*'
            flag1 = re1.test($('.num_show').val());
            if(flag1) {
                num = parseInt($('.num_show').val());
                if(num>=parseInt($('#stock').val())){
                    num = $('#stock').val()
                }else if(num<=1){
                    num = 1
                }
                total_prize = (num * {{ good.gprice }}).toFixed(2);
                $('.num_show').val(num);
                $('.total em').text(total_prize+'元');
            }else{
                $('.num_show').val(1)
            }
        })
        $('.add').click(function () {
            num = parseInt($('.num_show').val());
                if(num>=parseInt($('#stock').val())){
                    num = $('#stock').val()
                }else {
                    num++;
                }
            total_prize = (num * {{ good.gprice }}).toFixed(2);
            $('.num_show').val(num);
            $('.total em').text(total_prize+'元');
        });
        $('.minus').click(function () {
            num = parseInt($('.num_show').val());
            if(num<=1){
                num=1;
            }else {
                num--;
            }
            total_prize = (num * {{ good.gprice }}).toFixed(2);
            $('.num_show').val(num);
            $('.total em').text(total_prize+'元');
        });
        })

	</script>
{% endblock right %}



ttsx/templates/father.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	{% block title %}{% endblock title %}
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
    <script>
        $(function () {
        if($('.login_btn').text().indexOf('登录')<0){
            $.get('/cart/count1/',function (data) {
                $('#show_count').html(data.sum_count);
            });
        }
    })
    </script>
</head>
<body>

{#判断头部顶栏是否显示#}
{% if head == 1 %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.session.uname %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ request.session.uname }}</em>
                     <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:user_center_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endif %}
{#搜索框在中间#}
{% if logo_search == 1 %}
<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
            <form method='get' action="/search/" target="_blank">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>
{#搜索框在右边#}
{% elif logo_search == 2 %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
		<div class="search_con fr">
            <form method='get' action="/search/" target="_blank">
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="submit" class="input_btn fr" value="搜索">
            </form>
		</div>
	</div>

{% endif %}
{% block body %}{% endblock body %}

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

</body>
</html>

ttsx/templates/father2.html
{% extends 'father.html' %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="{% url 'goods:index' %}">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="{% url 'goods:index' %}">抽奖</a></li>
			</ul>
		</div>
	</div>
    {% block list_title %}{% endblock list_title %}


    <div class="main_wrap clearfix">
{% block left %}
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new in new_list %}
					<li>
						<a href="/{{ new.id }}/"><img src="/static/{{ new.gimg }}"></a>
						<h4><a href="/{{ new.id }}/">{{ new.gname }}</a></h4>
						<div class="prize">￥{{ new.gprice }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>
{% endblock left %}
    {% block right %}{% endblock right %}
    </div>

{% endblock body %}

ttsx/templates/index.html
{% extends 'father.html' %}

    {% block title %}<title>
        天天生鲜-{{ title }}</title>
    	<script type="text/javascript" src="/static/js/slide.js"></script>

    {% endblock title %}

	{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for t in type_list %}
                <li><a href="#model0{{ forloop.counter }}" class="fruit">{{ t.tname }}</a></li>
            {% endfor %}
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points">
                <li class="active"></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>
{% for l in list_dic %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ l.t.tname }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for top_good in l.top_goods %}
                    <a href="/{{ top_good.id }}/">{{ top_good.gname|truncatechars:10 }}</a>
                {% endfor %}
{#				<a href="#">鲜芒</a>#}
{#				<a href="#">加州提子</a>#}
{#				<a href="#">亚马逊牛油果</a>#}
			</div>
			<a href="{% url 'goods:list' tid=l.t.id pIndex=1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>


		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner0{{ forloop.counter }}.jpg"></div>
			<ul class="goods_list fl">
                {% for new_good in l.new_goods %}
				<li>
					<h4><a href="/{{ new_good.id }}/">{{ new_good.gname }}</a></h4>
					<a href="/{{ new_good.id }}/"><img src="/static/{{ new_good.gimg }}/"></a>
					<div class="prize">{{ new_good.gprice }}</div>
				</li>
                {% endfor %}

			</ul>
		</div>

	</div>

{% endfor %}
	    <script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock body %}


ttsx/templates/list.html
{% extends 'father2.html' %}

	{% block title %}<title>天天生鲜-{{ title }}</title>{% endblock title %}

{% block list_title %}
	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:index' %}">{{ t.tname }}</a>
	</div>
{% endblock list_title %}

{% block right %}
		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
{#            {% url 'goods:list' tid=t.id pIndex=now_page.number kind=0 %}#}
				<a href="?kind=0" {% if kind == '0' %}class="active"{% endif %}>默认</a>
				<a href="?kind=1&order={{ order|default:1 }}" {% if kind == '1' %}class="active"{% endif %}>价格</a>
				<a href="?kind=2&order={{ order|default:1 }}" {% if kind == '2' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for good in now_page %}
				<li>
					<a href="{% url 'goods:detail' tid=t.id gid=good.id %}"><img src="/static/{{ good.gimg }}"></a>
					<h4><a href="{% url 'goods:detail' tid=t.id gid=good.id %}">{{ good.gname }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.gprice }}</span>
						<span class="unit">{{ good.gprice }}/{{ good.gunit }}</span>
						<a href="javascript:add_cart1({{ good.id }});" class="add_goods" id='add_cart' title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
            {% if now_page.has_previous %}
                <a href="{% url 'goods:list' tid=t.id pIndex=1 %}">首页</a>
				<a href="{% url 'goods:list' tid=t.id pIndex=now_page.number|add:-1 %}"><上一页</a>
            {% endif %}
            {% if p.num_pages > 5 %}
                {% if index_list.4 > 5 %}
                        <a href="">...</a>
                {% endif %}
            {% endif %}
                {% for i in index_list %}
                    {% if i == now_page.number %}
                        <a href="{% url 'goods:list' tid=t.id pIndex=i %}" class="active">{{ i }}</a>
                    {% else %}
                        <a href="{% url 'goods:list' tid=t.id pIndex=i %}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
            {% if p.num_pages > 5 %}
                {% if p.num_pages|add:-1 > index_list.4 %}
                    <a href="">...</a>
                {% endif %}
            {% endif %}
            {% if now_page.has_next %}
				<a href="{% url 'goods:list' tid=t.id pIndex=now_page.number|add:1 %}">下一页></a>
                <a href="{% url 'goods:list' tid=t.id pIndex=p.num_pages %}">末页</a>
            {% endif %}
			</div>
		</div>
        <div class="add_jump"></div>

    <script>
    function add_cart1(gid) {
        $.get('/cart/islogin/',function (data) {
            if(data.flag1){//已经登录
{#                添加的函数#}
                $.get('/cart/add/',{'gid':gid},function (data) {
                    if(data.result){//添加成功
                        {#              播放添加购物车的动画#}
                        var $add_x = $('#add_cart').offset().top;
                        var $add_y = $('#add_cart').offset().left;

                        var $to_x = $('#show_count').offset().top;
                        var $to_y = $('#show_count').offset().left;

                        $('#add_cart').click(function(){
                            $(".add_jump").css({'left':$add_y,'top':$add_x,'display':'block'});
                            $(".add_jump").stop().animate({
                                'left': $to_y+7,
                                'top': $to_x+7},
                                "fast", function() {
                                    $(".add_jump").fadeOut('fast',function(){
                                        var cart_all = $('#show_count').text();
                                        $('#show_count').html(parseInt(cart_all)+data.gcount);
                                    });
                            });
                        })
                    }else{//添加失败
                        alert('添加失败');
                    }
                });
            }else{//未登录
                location.href = '/user/login/';
            }
        });
    }

    </script>
{% endblock right %}


ttsx/templates/login.html

{% extends 'father.html' %}
{% load staticfiles %}
	{% block title %}<title>天天生鲜-{{ title }}</title>{% endblock title %}
{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'user:login' %}" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" action="{% url 'user:login_check' %}">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ uname }}">
						<div class="user_error">{{ error_name }}</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">{{ error_pwd }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="user_remember" value="1" checked="checked">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="login_submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

ttsx/templates/register.html
{% extends 'father.html' %}
	{% block title %}<title>天天生鲜-{{ title }}</title>{% endblock title %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register_check' %}" id="reg_form">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name" value="{{ uname }}">
						<span class="error_tip">{{ error_name }}</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd" value="{{ passwd }}">
						<span class="error_tip">{{ error_pwd }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd" value="{{ passwd_confirm }}">
						<span class="error_tip"></span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email" value="{{ uemail }}">
						<span class="error_tip">{{ error_email }}</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">{{ error_allow }}</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" >
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
{% endblock body %}

ttsx/templates/user_center_info.html
{% extends 'father.html' %}

	{% block title %}<title>天天生鲜-{{ title }}</title>{% endblock title %}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user_center_info/" class="active">· 个人信息</a></li>
				<li><a href="/user_center_order/">· 全部订单</a></li>
				<li><a href="/user_center_site/">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							<li><span>联系方式：</span>{{ user.tel|default:'&nbsp&nbsp&nbsp' }}</li>
							<li><span>联系地址：</span>{{ user.address|default:'&nbsp&nbsp&nbsp' }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for see in goods %}
                            <li>
{#                            {% url 'user:detail' tid=t.id gid=good.id%}#}
                                <a href=""><img src="/static/{{ see.gimg }}/"></a>
                                <h4><a href="">{{ see.gname }}</a></h4>
                                <div class="operate">
                                    <span class="prize">￥{{ see.gprice }}</span>
                                    <span class="unit">{{ see.gprice }}/{{ see.gunit }}</span>
                                    <a href="/user_center_info/" class="add_goods" title="加入购物车"></a>
                                </div>
                            </li>
                        {% endfor %}

			</ul>
		</div>
		</div>
	</div>
{% endblock body %}
